version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.VSSDK.BuildTools
    versions:
    - 16.10.10
    - 16.10.23
    - 16.10.31
    - 16.10.7
    - 16.9.1044
    - 16.9.1050
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: SmartFormat.NET
    versions:
    - 2.5.3
    - 2.6.1
    - 2.6.2
  - dependency-name: EnvDTE
    versions:
    - 16.7.30508.193
  - dependency-name: Microsoft.VisualStudio.SDK.Analyzers
    versions:
    - 16.7.9
